name: First Contribution
description: Automatically respond to a user's first contribution to your repository.
author: Paul Ebose

branding:
  icon: activity
  color: green

inputs:
  token:
    description: GitHub token used to post comments, labels, and reactions. Defaults to `github.token`.
    default: ${{ github.token }}
  issue-opened-msg:
    description: Message when a first-time contributor opens an issue.
  pr-opened-msg:
    description: Message when a first-time contributor opens a pull request.
  issue-completed-msg:
    description: Message for a first-time contributor when their issue is closed as completed.
  issue-not-planned-msg:
    description: Message for a first-time contributor when their issue is closed as not planned.
  pr-merged-msg:
    description: Message for a first-time contributor when their pull request is merged.
  pr-closed-msg:
    description: Message for a first-time contributor when their pull request is closed without being merged.
  labels:
    description: Comma-separated list of labels to add when an issue or PR is opened.
  issue-labels:
    description: Comma-separated list of labels for first-time issues. Overrides `labels`.
  pr-labels:
    description: Comma-separated list of labels for first-time pull requests. Overrides `labels`.
  reactions:
    description: >
      Comma-separated list of emoji reactions to add to the issue or PR body. Must be one of: `+1`, `-1`, `laugh`,
      `confused`, `heart`, `hooray`, `rocket`, `eyes`.
  issue-reactions:
    description: >
      Comma-separated list of emoji reactions to add to the issue body. Overrides `reactions` input. Must be one of:
      `+1`, `-1`, `laugh`, `confused`, `heart`, `hooray`, `rocket`, `eyes`.
  pr-reactions:
    description: >
      Comma-separated list of emoji reactions to add to the pull request body. Overrides `reactions` input. Must be one
      of: `+1`, `-1`, `laugh`, `confused`, `heart`, `hooray`, `rocket`, `eyes`.
  contribution-mode:
    description: |
      Controls how first contributions are tracked.
      - (default): Issues and pull requests are tracked separately. The Action triggers for a user's first issue AND their first pull request.
      - `once`: The Action triggers only on the user's very first contribution to the repository, whether it's an issue OR a pull request.
  fail-on-error:
    description: Fail the workflow step if an error occurs.
    default: 'false'

outputs:
  type:
    description: Contribution type. `issue` or `pr`.
  number:
    description: Issue or pull request number.
  username:
    description: GitHub username of the contributor.
  comment-url:
    description: URL of the posted comment.

runs:
  using: node24
  main: dist/index.js
