name: First Contribution
description: Automatically respond to a user's first contribution to your repository.
author: Paul Ebose

branding:
  icon: activity
  color: green

inputs:
  token:
    description:
      The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to add comments and labels. Defaults to `github.token`.
    default: ${{ github.token }}
  issue-opened-msg:
    description: Message for a first-time contributor when they open a new issue.
  pr-opened-msg:
    description: Message for a first-time contributor when they open a new pull request.
  issue-completed-msg:
    description: Message for a first-time contributor when their issue is closed as completed.
  issue-not-planned-msg:
    description: Message for a first-time contributor when their issue is closed as not planned.
  pr-merged-msg:
    description: Message for a first-time contributor when their pull request is merged.
  pr-closed-msg:
    description: Message for a first-time contributor when their pull request is closed without being merged.
  labels:
    description: Comma-separated list of labels to add to an issue or PR from a first-time contributor.
  issue-labels:
    description: Comma-separated list of labels for a first-time issue. Takes precedence over the `labels` input.
  pr-labels:
    description: Comma-separated list of labels for a first-time pull request. Takes precedence over the `labels` input.
  contribution-mode:
    description: |
      Controls how first contributions are tracked.
      - (default): Issues and pull requests are tracked separately. The action triggers for a user's first issue AND their first pull request.
      - `once`: The action triggers only on the user's very first contribution to the repository, whether it's an issue OR a pull request.
  fail-on-error:
    description:
      If `true`, the action will fail the workflow step if an error occurs. If `false`, it will log the error without
      failing.
    default: 'false'
  reactions:
    description: >
      A comma-separated list of emoji reactions to add to the issue or PR body. Must be one of: `+1`, `-1`, `laugh`,
      `confused`, `heart`, `hooray`, `rocket`, `eyes`.
  issue-reactions:
    description: >
      Comma-separated list of emoji reactions to add to the issue body. Takes precedence over the `reactions` input.
      Must be one of: `+1`, `-1`, `laugh`, `confused`, `heart`, `hooray`, `rocket`, `eyes`.
  pr-reactions:
    description: >
      Comma-separated list of emoji reactions to add to the pull request body. Takes precedence over the `reactions`
      input. Must be one of: `+1`, `-1`, `laugh`, `confused`, `heart`, `hooray`, `rocket`, `eyes`.

outputs:
  type:
    description: Where the first contribution was made. `issue` or `pr`.
  number:
    description: The number of the issue or pull request.
  username:
    description: The GitHub username of the first-time contributor.
  comment-url:
    description: URL of the comment posted in response to the user's first contribution.

runs:
  using: node24
  main: dist/index.js
