allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - cpd-darwin-arm64@5.0.8
  - cpd-darwin-x64@5.0.8
  - cpd-linux-arm64-gnu@5.0.8
  - cpd-linux-x64-gnu@5.0.8
  - cpd-linux-x64-musl@5.0.8
  - cpd-windows-x64-msvc@5.0.8
  - jscpd@5.0.8
