#!/bin/bash

# generate jscpd reports (built-in)
pnpm exec jscpd --reporters 'badge,markdown'

# generate coverage & vitest reports
pnpm exec vitest --run --coverage --reporter=json --outputFile.json=.vitest-reports/report.json
./scripts/gen-coverage-and-tests-reports
