#!/bin/bash

# generate jscpd reports (built-in)
pnpm exec jscpd --reporters 'badge,markdown'

# Ignore super-linter NATURAL_LANGUAGE error for "typescript" word
ex assets/jscpd-report.md <<eof
1 insert
<!-- textlint-disable -->
.
xit
eof


# generate coverage & vitest reports
pnpm exec vitest --run --coverage --reporter=json --outputFile.json=.vitest-reports/report.json
./scripts/gen-coverage-and-tests-reports
